name: 📖 Documentation Feature
description: Add Documentation for New Feature
title: "[Docs]: "
labels: ["Documentation", "User Education Pod"]
assignees:
- Nikhil-Nandagopal
- jnikhila
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this documentation request!
- type: checkboxes
  id: checkFeatureExistingIssues
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue related to this already exists.
    options:
    - label: I have searched the existing issues
      required: true
- type: input
  id: engineeringTicketLink
  attributes:
    label: Engineering Ticket Link
    description: Add a link to the engineering ticket 
  validations:
    required: false
- type: input
  id: featureReleaseDate
  attributes:
    label: Release Date
    description: Add actual/tentative release date
  validations:
    required: false
- type: input
  id: featureReleaseNumber
  attributes:
    label: Release Number
    description: Add actual/tentative release number
  validations:
    required: false
- type: input
  id: FirstDraftLink
  attributes:
    label: First Draft 
    description: Add a link to the first draft created by engineers
  validations:
    required: false
- type: input
  id: loomVideoLink
  attributes:
    label: Loom video
    description: Add a link to the loom video explaining the feature 
  validations:
    required: false
- type: input
  id: forumLink
  attributes:
    label: Discord/slack/intercom Link if needed
    description: Add a link to the discussion 
  validations:
    required: false
- type: input
  id: PRD
  attributes:
    label: PRD
    description: Add a link to PRD if available
  validations:
    required: false
- type: input
  id: testplan
  attributes:
    label: Test plan/cases
    description: Add a link to test plan/cases if available
  validations:
    required: false
- type: textarea
  id: userRequests
  attributes:
    label: Use cases or user requests 
    description: Add a summary of use cases/user requests around which the doc can be built
  validations:
    required: false
