name: 📖 Documentation Improvement
description: Use this template to suggest improvements for our documentation.
title: "[Docs]: "
labels: ["Documentation" , "User Education Pod"]
assignees:
- Nikhil-Nandagopal
- jnikhila
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this documentation improvement request!
- type: checkboxes
  id: checkExistingIssues
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue related to this already exists.
    options:
    - label: I have searched the existing issues
      required: true
- type: input
  id: docLink
  attributes:
    label: Documentation Link 
    description: Add a link to the page which needs improvement (if relevant)
  validations:
    required: false
- type: input
  id: communityForumLink
  attributes:
    label: Discord/slack/intercom Link 
    description: Add a link to the discussion 
  validations:
    required: false
- type: textarea
  id: whatHappened
  attributes:
    label: Describe the problem and improvement.
    description: Please provide more context or specify the content that needs to be rewritten. 
  validations:
    required: true
