extends: existence
message: "Avoid using acronyms in a title or heading."
link: https://docs.microsoft.com/en-us/style-guide/acronyms#be-careful-with-acronyms-in-titles-and-headings
level: warning
scope: heading
tokens:
  - '[A-Z]{2,4}'
exceptions:
  - API
  - URL
  - JSON
  - JS
  - UI
  - SSL
  - BE
  - EFS
  - PVC
  - CE
  - BE
  - ECS
