extends: capitalization
message: "'%s' should use sentence-style capitalization."
link: 'https://developers.google.com/style/capitalization#capitalization-in-titles-and-headings'
level: warning
scope: 
- heading.h2
- heading.h3
- heading.h4
- heading.h5
- heading.h6
match: $sentence
indicators:
  - ':'
exceptions:
  - Azure
  - CLI
  - Code
  - Cosmos
  - Docker
  - Emmet
  - gRPC
  - I
  - Kubernetes
  - Linux
  - macOS
  - Marketplace
  - MongoDB
  - REPL
  - Studio
  - TypeScript
  - URLs
  - Visual
  - VS
  - Windows
  - API
  - APIs
  - Helm
  - JS Object
  - JS Objects
  - JavaScript
 
