extends: capitalization
message: "'%s' should use sentence-style capitalization."
link: 'https://developers.google.com/style/capitalization#capitalization-in-titles-and-headings'
level: warning
scope: 
- heading.h2
- heading.h3
- heading.h4
- heading.h5
- heading.h6
match: $sentence
indicators:
  - ':'
exceptions:
  - Azure
  - CLI
  - Code
  - Cosmos
  - Docker
  - Emmet
  - gRPC
  - Document
  - Documents
  - Connection String URI
  - URIs
  - I
  - Kubernetes
  - Linux
  - macOS
  - Marketplace
  - MongoDB
  - REPL
  - Studio
  - TypeScript
  - URLs
  - Visual
  - VS
  - Windows
  - API
  - APIs
  - Ingress
  - Button
  - Item
  - Menu
  - Items
  - Source
  - Data
  - Helm
  - JS Object
  - JS Objects
  - JavaScript
  - Keycloak
  - Redis
  - DigitalOcean
  - Docker
  - K8s   
  - Framework
  - Promises
  - Actions
  - Promise.allSettled()
  - Promise.all()
  - Promise.any()
  - Promise.race()
  - Async/Await
  - Amazon Web Services
  - SSH
  - Business Edition 
  - Community Edition
  - Connection Mode
  - Custom Domain
  - Custom SSL
  - SSL
  - HTTPS
  - Let's 
  - Encrypt
  - TLS
  - Stats Box
  - IFrame
  - Document Viewer
  - GraphQL
  - Table
  - Map
  - UI
  - Default Value
  - Show Marks
  - Value
  - Min
  - Max
  - Size
  - Always On
  - Range
  - Start
  - End
  - run()
  - Type
  - Token
  - JS
  - Records
  - Settings
  - Firestore
  - Project
  - ID
  - Database
  - Service
  - Account
  - Credentials
  - Single
  - Multiple
  - Collection
  - Pagination
  - Signed and Unsigned
  - Signed
  - File
  - Files
