extends: capitalization
message: "'%s' should be in title case"
level: warning
# Could be `heading.h2`, `heading.h3`, etc.
scope: heading.h1
match: $title
exceptions:
  - k8s 
  - is
  - to
  - clipboard