name: Check redirects

on:
  pull_request:
    paths:
      - 'website/vercel.json'
      - '.github/workflows/check-redirects.yml'
  push:
    branches: [main]
    paths:
      - 'website/vercel.json'
      - '.github/workflows/check-redirects.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-redirects:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
        shell: bash
    steps:
      - uses: actions/checkout@v7
      - name: Check invalid redirect rules
        run: |
          incorrect_paths="$(jq -r '.redirects[] | select(.source == .destination) | .source' vercel.json)"
          if [[ -n $incorrect_paths ]]; then
            echo "There are redirect rules with source = destination. Please correct them." >&2
            echo "$incorrect_paths" >&2
            exit 1
          fi
          repeated_sources="$(jq -r '.redirects[].source' vercel.json | sort | uniq -c -d)"
          if [[ -n $repeated_sources ]]; then
            echo "There are repeated sources in redirect rules. Please correct them." >&2
            echo "$repeated_sources" >&2
            exit 1
          fi
