name: Generate and Upload PDF

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  generate-and-upload-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies --legacy-peer-deps
        run: npm install
        working-directory: website

      - name: Install Prince
        run: |
          curl https://www.princexml.com/download/prince-14.2-linux-generic-x86_64.tar.gz -O
          tar zxf prince-14.2-linux-generic-x86_64.tar.gz
          cd prince-14.2-linux-generic-x86_64
          yes "" | sudo ./install.sh

      - name: Install Ghostscript
        run: sudo apt-get install -y ghostscript

      - name: Generate PDF
        run: npx docusaurus-prince-pdf -u https://docs.appsmith.com --output pdf/appsmith-docs.pdf
        working-directory: website

      - name: Check original PDF size
        run: ls -lh pdf/appsmith-docs.pdf
        working-directory: website

      - name: Compress PDF with Ghostscript
        run: |
          gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 \
          -dPDFSETTINGS=/screen -dNOPAUSE -dQUIET -dBATCH \
          -dDetectDuplicateImages=true -dDownsampleColorImages=true \
          -dColorImageResolution=10 -dGrayImageResolution=10 \
          -dMonoImageResolution=10 -sOutputFile=compressed-appsmith-docs.pdf pdf/appsmith-docs.pdf
        working-directory: website

      - name: Check compressed PDF size
        run: ls -lh compressed-appsmith-docs.pdf
        working-directory: website

      - name: Upload compressed PDF to API
        run: |
          response=$(curl -X POST \
            -H "Content-Type: application/pdf" \
            --data-binary "@compressed-appsmith-docs.pdf" \
            https://hook.eu1.make.com/78ylobuaxpwb4w8k3lbfgmdlwow9d8m5)
          echo "Response: $response"
        working-directory: website
