name: Lint

on: 
  pull_request:
    paths:
      - "website/docs/**.md"
      - "website/docs/**.mdx"

jobs:
  run_vale:
    runs-on: ubuntu-latest
         
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run vale linter
        uses: errata-ai/vale-action@reviewdog
        with:
          files: website/docs/
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
